# Generated by Django 3.0 on 2019-12-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('season', models.PositiveSmallIntegerField(choices=[(1, 'Winter'), (2, 'Summer'), (3, 'Rainy')])),
                ('water_requirement', models.IntegerField()),
                ('water_reapeat', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
