# Generated by Django 3.0 on 2019-12-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='is_food',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
