# Generated by Django 3.0 on 2020-06-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
