# Generated by Django 3.0 on 2019-12-10 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='address',
            new_name='location',
        ),
    ]
