# Generated by Django 3.0 on 2019-12-11 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0002_auto_20191211_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WaterResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('efficiency', models.IntegerField()),
                ('income_rate', models.IntegerField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Primary'), (2, 'Secondary')], default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='water_resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='farm.WaterResource'),
            preserve_default=False,
        ),
    ]
