# Generated by Django 3.0 on 2020-02-16 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_plots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterresource',
            old_name='efficiency',
            new_name='available_water',
        ),
    ]
