# Generated by Django 3.0 on 2020-02-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_auto_20200216_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='soil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='farm.Soil'),
            preserve_default=False,
        ),
    ]
