# Generated by Django 3.0 on 2020-02-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_auto_20191211_1337'),
        ('farm', '0006_farm_soil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ploting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.Crop')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Plots')),
            ],
        ),
    ]
