# Generated by Django 3.0 on 2020-02-16 08:52

from django.db import migrations, models
import django.db.models.deletion
import farm.models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_ploting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=farm.models.upload_file_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ploting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Ploting')),
            ],
        ),
    ]
