# Generated by Django 3.0 on 2020-02-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191211_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
