# Generated by Django 3.0 on 2020-02-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Farmer'), (2, 'Doctor'), (3, 'Shop')], default=1),
        ),
    ]
